### ISSUE TITLE
Dependencies Error

### ISSUE THREAD

**Issue by gru3zi** [nicokaiser/kaiser.gallery#16]
Hello,

Im quite new to Hugo and found your template really simple and nice. Im trying to build the site on my proxmox server but somehow keep running into this error. 

**Error: add site dependencies: load resources: loading templates: "/root/photography/kaiser.gallery/themes/gallery/layouts/partials/navbar-albums.html:11:1": parse failed: template: partials/navbar-albums.html:11: function "page" not defined**

Could you tell me if im doing something wrong? 

I made a copy of hugo.toml to config.toml and amended the BaseURL to a local IP - http://192.168.X.X/

I dont think I would have needed anything else to get started. 

Thank you for your time. 

Warm regards,

Marc

**Comment by nicokaiser** [comment]
Hi Marc! Could you check if you are using the right Hugo version? I think the theme requires at least v0.112.0.

**Comment by gru3zi** [comment]
Heres the output of the command Hugo Version

# hugo version 
Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: 2021-07-18T09:31:51Z (debian 0.80.0-6+b5)

**Comment by nicokaiser** [comment]
The Debian packaged versions of Hugo are too old, Debian 11 contains Hugo 0.80, Debian 12 contains Hugo 0.111, this theme requires >=0.112.

I can try to re-add the "hugo-extended" npm dependency, so Hugo is installed inside the node_modules folder in the correct version (Node modules need to be there anyway because of Tailwind CSS)...
